import { createFileRoute } from '@tanstack/react-router';
import { useServerFn } from '@tanstack/react-start';
import { useState, type FormEvent } from 'react';
import { useQuery } from '@tanstack/react-query';
import { LockKeyhole, RefreshCw, LogOut } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { listOrders, updateOrderStatus } from '@/lib/orders.functions';
import { rupees } from '@/data/menu';
import { pageHead } from '@/lib/seo';
export const Route = createFileRoute('/admin')({ head: () => pageHead('Staff orders | Frono – The Italiano', 'Secure staff access to incoming Frono orders.'), component: Admin });
function Admin() {
  const getOrders = useServerFn(listOrders); const update = useServerFn(updateOrderStatus);
  const [signedIn, setSignedIn] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const orders = useQuery({ queryKey: ['staff-orders'], queryFn: () => getOrders(), enabled: signedIn, retry: false, refetchInterval: signedIn ? 30000 : false });
  async function login(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(''); const form = new FormData(e.currentTarget); const { error } = await supabase.auth.signInWithPassword({ email: String(form.get('email')), password: String(form.get('password')) }); if (error) setError(error.message); else setSignedIn(true); setBusy(false); }
  if (!signedIn) return <div className="container-frono section-space"><form onSubmit={login} className="mx-auto max-w-sm space-y-5 py-10"><LockKeyhole className="size-9 text-primary" /><h1 className="section-title">Staff sign-in</h1><label className="form-field">Email<input name="email" type="email" required autoComplete="username" /></label><label className="form-field">Password<input name="password" type="password" required autoComplete="current-password" /></label>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button size="lg" className="w-full" disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}</Button></form></div>;
  return <div className="container-frono section-space"><div className="mb-8 flex flex-wrap items-center justify-between gap-4"><h1 className="section-title">Incoming orders</h1><div className="flex gap-2"><Button variant="outline" aria-label="Refresh orders" onClick={() => orders.refetch()}><RefreshCw />Refresh</Button><Button variant="ghost" onClick={async () => { await supabase.auth.signOut(); setSignedIn(false); }}><LogOut />Sign out</Button></div></div>{(error || orders.error) && <p role="alert" className="mb-5 text-destructive">{error || orders.error?.message}</p>}{orders.isLoading && <p>Loading orders…</p>}{orders.data?.length === 0 && <p className="py-12 text-muted-foreground">No orders yet.</p>}<div className="space-y-6">{orders.data?.map(order => <article key={order.id} className="rounded-xl border border-border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-lg text-primary">{order.order_number}</h2><p className="mt-1 text-xs text-muted-foreground">{new Date(order.created_at).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</p></div><label className="flex items-center gap-3 text-sm">Status<select className="admin-select" value={order.status} aria-label={`Status for ${order.order_number}`} onChange={async e => { setError(''); try { await update({ data: { id: order.id, status: e.target.value } }); await orders.refetch(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update order'); } }}>{['New','Preparing','Ready','Completed'].map(s => <option key={s}>{s}</option>)}</select></label></div><div className="mt-4 grid gap-5 text-sm md:grid-cols-2"><div><p className="font-bold">{order.customer_name} · {order.order_type}</p><a href={`tel:${order.phone}`} className="mt-2 inline-block">{order.phone}</a>{order.address && <p className="mt-2">{order.address}</p>}{order.notes && <p className="mt-2 text-muted-foreground">Notes: {order.notes}</p>}</div><div>{Array.isArray(order.items) && order.items.map((raw, n) => { if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null; return <p key={n}>{String(raw['quantity'])} × {String(raw['name'])}</p>; })}<p className="mt-3 font-extrabold text-primary">{rupees(Number(order.total))} · Pay on {order.order_type.toLowerCase()}</p></div></div></article>)}</div></div>;
}