import { createFileRoute } from "@tanstack/react-router";
import { Link } from '@tanstack/react-router';
import { ArrowUpRight, ArrowRight, Pizza, Leaf, Heart, MapPin, Instagram, Clock, Utensils, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { DishCard } from '@/components/dish-card';
import { featuredItems } from '@/data/menu';
import { pageHead } from '@/lib/seo';
const hero = '/images/pizza.jpg';
const pizza = '/images/pizza.jpg';
const pasta = '/images/pasta.jpg';
const bread = '/images/bread.jpg';
const dessert = '/images/dessert.jpg';
const coffee = '/images/coffee.jpg';
const interior = '/images/interior.jpg';
import { RESTAURANT_ADDRESS, RESTAURANT_PHONE, WHATSAPP_NUMBER, OPENING_HOURS, INSTAGRAM_URL } from '@/config';
export const Route = createFileRoute("/")({
  head: () => pageHead('Frono – The Italiano | Authentic Italian in Vasna-Bhayli, Vadodara', 'Authentic Italian tastes & global family favorites at Frono in Vasna-Bhayli, Vadodara. Explore pizza, pasta and more. Order for pickup or delivery.'),
  component: Index,
});
function Index() {
  return <>
    <section className="hero-section"><img src={hero} alt="Fresh Italian pizza coming out of a wood-fired oven" className="hero-photo" fetchPriority="high" /><div className="hero-shade" /><div className="container-frono"><div className="hero-copy fade-in"><div className="eyebrow mb-6 text-highlight"><span className="h-px w-6 bg-highlight" /> A little Italy. A lot of love.</div><h1>Authentic Italian.<br /><span>Family Favorites.</span></h1><p className="mt-6 text-primary-foreground/85">Authentic Italian tastes & global family favorites.<br />Good food. Great company. A table for everyone.</p><div className="mt-8 flex flex-wrap gap-3"><Button variant="pizza" size="lg" asChild><Link to="/menu">Order Now <ArrowUpRight /></Link></Button><Button variant="hero" size="lg" asChild><Link to="/menu">View Menu <Utensils /></Link></Button></div><div className="mt-9 flex items-center gap-2 text-[11px] text-primary-foreground/80"><MapPin className="size-4 text-highlight" /> Vasna-Bhayli, Vadodara <span className="mx-2 text-secondary">•</span> Made with amore</div></div></div><div className="hero-stamp" aria-hidden="true"><Pizza /><span>LOVE AT FIRST BITE</span></div></section>
    <div className="info-strip"><div className="container-frono info-strip-inner"><div><Leaf className="size-4" /> Fresh ingredients</div><div><Pizza className="size-4" /> Italian at heart</div><div><Heart className="size-4" /> Something for everyone</div><div><ShoppingIcon /> Pickup & delivery</div></div></div>
    <section className="container-frono section-space"><div className="mb-8 flex items-end justify-between gap-4"><div><div className="eyebrow mb-3 text-muted-foreground">From our kitchen, with love</div><h2 className="section-title shadow-heading">Meet your new favorites.</h2><p className="mt-3 text-xs text-muted-foreground">The classics you love. The flavors you’ll come back for.</p></div><Button variant="link" asChild className="hidden sm:inline-flex"><Link to="/menu">Explore full menu <ArrowRight /></Link></Button></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">{featuredItems.map(item => <DishCard key={item.id} item={item} featured />)}</div><Button variant="link" asChild className="mt-6 sm:hidden"><Link to="/menu">Explore full menu <ArrowRight /></Link></Button></section>
    <section id="about" className="about-section section-space"><div className="container-frono grid items-center gap-12 md:grid-cols-2"><img src={pasta} alt="Freshly prepared Italian pasta with basil" className="about-image" loading="lazy" /><div><div className="eyebrow mb-4 text-highlight"><Heart className="size-4" /> Our kind of Italian</div><h2 className="section-title">Italian soul.<br />A family kind of feeling.</h2><p className="mt-5 text-sm leading-8 text-primary-foreground/80">At Frono, we believe the best moments happen around a table. We’re a friendly Italian kitchen bringing together authentic Italian dishes and global favorites that everyone in the family can love.</p><p className="mt-3 text-sm leading-8 text-primary-foreground/80">From cheesy first bites to sweet last spoonfuls, there’s always a little something for everyone. Come hungry. Leave happy.</p><Button variant="pizza" size="lg" asChild className="mt-6"><Link to="/menu">Find your favorite <ArrowUpRight /></Link></Button></div></div></section>
    <section id="gallery" className="container-frono section-space"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><div className="eyebrow mb-3 text-muted-foreground">A taste of Frono</div><h2 className="section-title shadow-heading">Good food. Happy moments.</h2></div><a href={INSTAGRAM_URL} target="_blank" rel="noreferrer" className="flex items-center gap-2 text-xs font-semibold text-primary"><Instagram className="size-4" /> @frono.the_italiano <ArrowUpRight className="size-4" /></a></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3">{[{asset:pizza,alt:'Fresh basil pizza'},{asset:pasta,alt:'Italian pasta'},{asset:interior,alt:'Restaurant atmosphere inspiration'},{asset:bread,alt:'Golden garlic bread'},{asset:dessert,alt:'A slice of tiramisu'},{asset:coffee,alt:'Freshly made cold coffee'}].map(i => <img key={i.alt} src={i.asset} alt={i.alt} className="gallery-photo" loading="lazy" />)}</div><div className="mt-7 text-center"><Button variant="outline" asChild><a href={INSTAGRAM_URL} target="_blank" rel="noreferrer"><Instagram /> Follow us on Instagram <ArrowUpRight /></a></Button></div></section>
    <section id="contact" className="section-space border-t border-border bg-muted"><div className="container-frono grid items-center gap-9 md:grid-cols-2"><div><div className="eyebrow mb-3 text-muted-foreground">Your next happy place</div><h2 className="section-title shadow-heading">See you at Frono.</h2><div className="mt-7 space-y-5 text-sm"><p className="flex gap-3"><MapPin className="size-5 shrink-0 text-primary" />{RESTAURANT_ADDRESS}</p><p className="flex gap-3"><Clock className="size-5 shrink-0 text-primary" />{OPENING_HOURS}</p>{RESTAURANT_PHONE ? <a href={`tel:${RESTAURANT_PHONE}`}>{RESTAURANT_PHONE}</a> : <p className="text-muted-foreground">Contact details coming soon</p>}</div>{WHATSAPP_NUMBER && <Button asChild className="mt-6"><a href={`https://wa.me/${WHATSAPP_NUMBER}`} target="_blank" rel="noreferrer">Chat on WhatsApp</a></Button>}</div><iframe title="Map of Vasna-Bhayli, Vadodara" src="https://maps.google.com/maps?q=Vasna%20Bhayli%20Vadodara&output=embed" className="h-72 w-full rounded-xl border border-border" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></section>
  </>;
}
function ShoppingIcon() { return <Utensils className="size-4" />; }
